
services:
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - 5432:5432

  backend:
    build: .
    command: fastapi dev app.py --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # depends_on:
    #   - db
    env_file:
      - .env
    environment:
      - DB_ENGINE=sqlite
      - DB_NAME=db.sqlite3
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - orchid

networks:
  orchid:
    name: orchid_network
    external: true
